export const SELECT_TRACK = "SELECT_TRACK";
export const PLAY_SELECTED_TRACK = "PLAY_SELECTED_TRACK";
export const PAUSE_SELECTED_TRACK = "PAUSE_SELECTED_TRACK";
export const PLAY_NEXT_TRACK = "PLAY_NEXT_TRACK";
export const PLAY_PREV_TRACK = "PLAY_PREV_TRACK";
